- hosts: localhost
  tasks:

#nodejs
  - name: Build image NodeJS
    docker_image:
       path: ./
       dockerfile: Dockerfiles/Dockerfile_node
       name: ysoffner/app_nodejs

#nginx
  - name: Build image Nginx
    docker_image:
       path: ./
       dockerfile: Dockerfiles/Dockerfile_nginx
       name: ysoffner/app_nginx

  - name: Create a network with options
    docker_network:
      name: ysoffner_net

  - name: Start container, connect to network and link
    docker_container:
      name: app_nodejs
      image: ysoffner/app_nodejs
      networks:
        - name: ysoffner_net

  - name: Start container, NGINX
    docker_container:
      name: app_nginx
      image: ysoffner/app_nginx
      networks:
        - name: ysoffner_net